// Request User repos
export const USER_SET = 'USER_SET'
export const LOGIN_SET = 'LOGIN_SET'

export const FETCH_USERS_START = 'FETCH_USERS_START'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED'

export const FETCH_USER_INFO_START = 'FETCH_USER_INFO_START'
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS'
export const FETCH_USER_INFO_FAILED = 'FETCH_USER_INFO_FAILED'

export const FETCH_USER_REPO_START = 'FETCH_USER_REPO_START'
export const FETCH_USER_REPO_SUCCESS = 'FETCH_USER_REPO_SUCCESS'
export const FETCH_USER_REPO_FAILED = 'FETCH_USER_REPO_FAILED'

export const GET_USER = 'GET_USER'

export const EMPTY_ACTION = 'EMPTY_ACTION'
